# Change these first
owner: Flagmaker-Print # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Production
    url: $PROD_URL
  - name: Beta
    url: $BETA_URL
    expectedStatusCodes:
      - 403
      - 200
      - 304 

status-website:
  theme: night
  cname: status.flagmaker-print.com
  logoUrl: https://i.imgur.com/WSjrfU9.jpg
  name: Flagmaker & Print status
  introTitle: "**Flagmaker & Print Status**"
  introMessage: Here you can view the status of our websites 
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://flagmaker-print.com/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
